### ISSUE TITLE
Not Scrolling When Position fixed

### ISSUE THREAD

**Issue by tommoholmes** [gromo/jquery.scrollbar#56]
I have code css like that
``` css
#filter{
	width: 20%;
	min-height: 1px;
	padding-right: 0px;
	padding-left: 1px;
	margin-top: 34px;
	margin-left: 8px;
	z-index: 2;
	position: fixed;
	overflow: auto;
	max-height: 300px;
}
```
but scrollbar not display and its change my css
